language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - docker

before_script: pip3 install docker-compose

script:
  -docker-compose run app sh -c "python3 manage.py test && flake8"